name: Nix Build

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  llvm:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src-no-ccache.llvm-standalone.llvm
          display-name: "Intel Open Source DPC++ Compiler (Non-Monolithic, Core)"

  llvm-tools-stage1:
    runs-on: ubuntu-latest
    needs: llvm
    strategy:
      matrix:
        component: [clang, xpti, xptifw, opencl-aot]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src-no-ccache.llvm-standalone.${{ matrix.component }}
          display-name: "Intel Open Source DPC++ Compiler (Non-Monolithic, ${matrix.component})"

  llvm-tools-stage2:
    runs-on: ubuntu-latest
    needs: llvm-tools-stage1
    strategy:
      matrix:
        component: [stdenv, libclc, sycl]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src-no-ccache.llvm-standalone.${{ matrix.component }}
          display-name: "Intel Open Source DPC++ Compiler (Non-Monolithic, ${matrix.component})"

  llvm-mono:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src-no-ccache.llvm-monolithic
          display-name: "Intel Open Source DPC++ Compiler (Monolithic)"

  oneapi-src:
    runs-on: ubuntu-latest
    needs: llvm-mono
    strategy:
      matrix:
        component: [oneDNN, oneMath]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src-no-ccache.${{ matrix.component }}
          display-name: ${{ matrix.component }}

  khronos-sycl-cts:
    runs-on: ubuntu-latest
    needs: llvm-mono
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src-no-ccache.khronos-sycl-cts
          display-name: Khronos SYCL Conformance Test Suite

  ggml:
    runs-on: ubuntu-latest
    needs: oneapi-src
    strategy:
      matrix:
        component: [ggml, whisper-cpp, llama-cpp]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src-no-ccache.${{ matrix.component }}
          display-name: ${{ matrix.component }}
